-- Supabase Staff Data Seed Script
-- Run this in your Supabase SQL Editor: https://supabase.com/dashboard/project/_/sql

-- Clear existing staff data (Optional - uncomment to replace)
-- DELETE FROM staff;

INSERT INTO staff (id, name, role, bio, image, type, is_enabled) VALUES
('1', 'FR. NELSON A. D''SILVA, SJ', 'MANAGER, TREASURER', 'Appointed: 01-05-2021. Status: Confirmed. Full Time. Trained.', 'https://picsum.photos/seed/nelson/400/400', 'Management', true),
('2', 'FR. M. AROCKIAM, SJ', 'PRINCIPAL', 'Appointed: 01-07-2018. Status: Confirmed. Full Time. Trained.', 'https://picsum.photos/seed/arockiam/400/400', 'Management', true),
('3', 'FR. MADALAIMUTHU ANTHONIAPPAN, SJ ( Fr. BRITTO )', 'COORDINATOR ( MIDDLE SCHOOL )', 'Appointed: 01-07-2024. Status: Confirmed. Full Time. Trained.', 'https://picsum.photos/seed/britto/400/400', 'Administration', true),
('4', 'SR. RUTH MARIAM, SCJM', 'COORDINATOR ( JUNIOR SCHOOL )', 'Appointed: 01-04-2025. Status: Confirmed. Full Time. Trained.', 'https://picsum.photos/seed/ruth/400/400', 'Administration', true),
('5', 'MRS. KSHAMA SHARMA', 'COORDINATOR-ACADEMICS ( SENIOR SCHOOL )', 'Appointed: 01-04-2002. Status: Confirmed. Full Time. Trained.', 'https://picsum.photos/seed/kshama/400/400', 'Administration', true),
('6', 'MR. ALEX THOMAS', 'COORDINATOR-ACTIVITIES ( SENIOR SCHOOL )', 'Appointed: 01-08-1996. Status: Confirmed. Full Time. Trained.', 'https://picsum.photos/seed/alex/400/400', 'Administration', true),
('7', 'ABHISHEK MATHUR', 'PGT', 'Appointed: 01-07-2023. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('8', 'R. TRIVEDI', 'PGT', 'Appointed: 01-07-1994. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('9', 'SHAJI THOMAS', 'PGT', 'Appointed: 01-04-2003. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('10', 'DILIP SRIVASTAVA', 'PGT', 'Appointed: 01-07-2007. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('11', 'GOPAL SHARMA', 'PGT', 'Appointed: 01-07-2007. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('12', 'AJAY P. JOSE', 'PGT', 'Appointed: 01-04-2009. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('13', 'NIMMI SAM', 'PGT', 'Appointed: 06-07-2013. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('14', 'RAJENDRA JOSHI', 'PGT', 'Appointed: 01-07-1990. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('15', 'SUJITHA KUMAR', 'PGT', 'Appointed: 01-04-2006. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('16', 'VINEET BANSAL', 'PGT', 'Appointed: 01-04-2015. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('17', 'NELEMA J. SOLOMON', 'PGT', 'Appointed: 01-04-2016. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('18', 'NITIN ARORA', 'PGT', 'Appointed: 01-04-2016. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('19', 'LORRAINE DAVIS', 'PGT', 'Appointed: 01-04-2017. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('20', 'SHABANA AHMED', 'PGT', 'Appointed: 01-04-2017. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('21', 'KIRAN PAREEK', 'PGT', 'Appointed: 01-04-2018. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('22', 'RAJNI SINHA', 'PGT', 'Appointed: 01-07-2019. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('23', 'DEEKSHA CHHABRA', 'PGT', 'Appointed: 01-07-2020. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('24', 'SANGEETA JOSEPH', 'PGT', 'Appointed: 01-07-2022. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('25', 'NEHA WHITNEY', 'PGT', 'Appointed: 01-07-2025. Status: Contract. Full Time Trained Faculty.', '', 'Faculty', true),
('26', 'M. CASTELINO', 'TGT', 'Appointed: 01-07-1994. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('27', 'B. ACHARYA', 'TGT', 'Appointed: 01-07-1997. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('28', 'ASHOK SINGH KACHHWAHA', 'TGT', 'Appointed: 01-11-1999. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('29', 'PINKY VARGHESE', 'TGT', 'Appointed: 01-07-2000. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('30', 'S. SRIVASTAVA', 'TGT', 'Appointed: 01-07-2000. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('31', 'A. LAZER', 'TGT', 'Appointed: 01-10-2000. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('32', 'B. SHARMA', 'TGT', 'Appointed: 01-04-2001. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('33', 'KAMAYANI ATRE', 'TGT', 'Appointed: 01-04-2001. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('34', 'S GAUTAM', 'TGT', 'Appointed: 01-04-2002. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('35', 'SUMIT CHAUHAN', 'TGT', 'Appointed: 01-04-2002. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('36', 'MAMTA BATRA', 'TGT', 'Appointed: 01-07-2002. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('37', 'S. RATHORE', 'TGT', 'Appointed: 01-04-2003. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('38', 'NAVRATAN AGARWAL', 'TGT', 'Appointed: 01-04-2005. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('39', 'SAPNA SHARMA', 'TGT', 'Appointed: 01-04-2006. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('40', 'ARADHANA BHATNAGAR', 'TGT', 'Appointed: 01-04-2006. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('41', 'CHRISTINE UPASANA LOBO', 'TGT', 'Appointed: 01-04-2007. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('42', 'GOVIND NARAYAN SHARMA', 'TGT', 'Appointed: 01-07-2007. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('43', 'C.B. JOSE', 'TGT', 'Appointed: 01-04-2008. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('44', 'SAROJ NAUTIYAL', 'TGT', 'Appointed: 01-04-2008. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('45', 'MAMTA SHEKHAWAT', 'TGT', 'Appointed: 01-04-2009. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('46', 'ANANT AKASH HENRY', 'TGT', 'Appointed: 01-08-2010. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('47', 'POOJA SHERRY', 'TGT', 'Appointed: 01-04-2011. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('48', 'JINU GEORGE', 'TGT', 'Appointed: 01-04-2012. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('49', 'GOLDY BHARGAVA', 'TGT', 'Appointed: 01-07-2012. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('50', 'OLIVE E MALAKI', 'TGT', 'Appointed: 01-10-2014. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('51', 'SHRUTI PAREEK', 'TGT', 'Appointed: 01-07-2014. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('52', 'NAMRATA SOMANI', 'TGT', 'Appointed: 01-10-2014. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('53', 'JENNIFER BARNO', 'TGT', 'Appointed: 01-04-2016. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('54', 'CHHAYA SINGH', 'TGT', 'Appointed: 01-04-2017. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('55', 'JISS MARY GEORGE', 'TGT', 'Appointed: 01-04-2017. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('56', 'AKHILA R. NAIR', 'TGT', 'Appointed: 01-04-2017. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('57', 'SIJI JOSE', 'TGT', 'Appointed: 02-07-2018. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('58', 'SOBIN CHERIAN', 'TGT', 'Appointed: 01-07-2019. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('59', 'KHUSHBOO KHANGAROT', 'TGT', 'Appointed: 01-07-2022. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('60', 'STEPHIE CAROLENE MENDONCA', 'TGT', 'Appointed: 01-07-2022. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('61', 'BHUMIKA SHARMA', 'TGT', 'Appointed: 01-12-2024. Status: Contract. Full Time Trained Faculty.', '', 'Faculty', true),
('62', 'DIVYA SWARUP', 'TGT', 'Appointed: 01-07-2023. Status: Contract. Full Time Trained Faculty.', '', 'Faculty', true),
('63', 'K.B. ARUN', 'TGT', 'Appointed: 01-07-2025. Status: Contract. Full Time Trained Faculty.', '', 'Faculty', true),
('64', 'N. CHOPRA', 'PRT', 'Appointed: 01-07-1993. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('65', 'LALITA PAREEK', 'PRT', 'Appointed: 01-07-1994. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('66', 'M. ARORA', 'PRT', 'Appointed: 01-07-1997. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('67', 'PINKY GROVER', 'PRT', 'Appointed: 01-07-2001. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('68', 'MALVEA TRIBENI', 'PRT', 'Appointed: 01-04-2008. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('69', 'NEETU GAGAN SINGH', 'PRT', 'Appointed: 01-04-2008. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('70', 'VARSHA JAIN', 'PRT', 'Appointed: 01-04-2010. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('71', 'ELIZABETH THOMAS', 'PRT', 'Appointed: 01-04-2010. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('72', 'SONAL GUPTA', 'PRT', 'Appointed: 01-04-2010. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('73', 'SAPNA SHARMA', 'PRT', 'Appointed: 01-08-2010. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('74', 'VINITA YADAV', 'PRT', 'Appointed: 01-08-2010. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('75', 'AMALA JOHN', 'PRT', 'Appointed: 01-04-2011. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('76', 'ASHA JOHN', 'PRT', 'Appointed: 01-04-2011. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('77', 'VIBHA OJHA', 'PRT', 'Appointed: 01-04-2011. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('78', 'SANKRANTI BHARDWAJ', 'PRT', 'Appointed: 01-04-2012. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('79', 'NIDHI JAIN', 'PRT', 'Appointed: 01-04-2012. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('80', 'SHAISTA REHMAN', 'PRT', 'Appointed: 01-04-2012. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('81', 'RICHA KAPOOR', 'PRT', 'Appointed: 01-04-2012. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('82', 'SINDHU VARMA', 'PRT', 'Appointed: 01-04-2012. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('83', 'MEGHA MANAN MUKUL', 'PRT', 'Appointed: 01-04-2012. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('84', 'LIJI JAIN', 'PRT', 'Appointed: 01-04-2013. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('85', 'SUCHITA JACOB', 'PRT', 'Appointed: 01-04-2013. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('86', 'YOGITA MOUDGIL', 'PRT', 'Appointed: 01-07-2013. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('87', 'ARPITA BHARGAVA', 'PRT', 'Appointed: 01-04-2014. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('88', 'JINSY PHILIP', 'PRT', 'Appointed: 01-04-2014. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('89', 'NISHA BHATI', 'PRT', 'Appointed: 01-10-2014. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('90', 'RUPA SHUKLA', 'PRT', 'Appointed: 01-07-2014. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('91', 'SEEMA SHARMA', 'PRT', 'Appointed: 01-11-2013. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('92', 'A B PATHAK', 'PRT', 'Appointed: 01-04-2014. Status: Contract (Ad Hoc). Trained Faculty.', '', 'Faculty', true),
('93', 'SHIKHA SRIVASTAVA', 'PRT', 'Appointed: 01-04-2015. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('94', 'SR. LISSY KURIAN, SCJM', 'PRT', 'Appointed: 01-07-2025. Status: Confirmed (Ad Hoc). Trained Faculty.', '', 'Faculty', true),
('95', 'MANISHA DIXIT', 'PRT', 'Appointed: 01-08-2017. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('96', 'BLOSSOM BLISS FERNADES', 'PRT', 'Appointed: 01-07-2022. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('97', 'SHAZIA IRAM', 'PRT', 'Appointed: 01-07-2022. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('98', 'NANCY MANSINGH', 'PRT', 'Appointed: 01-07-2023. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('99', 'MAGDELENE LOBO', 'PRT', 'Appointed: 01-07-2023. Status: Confirmed. Full Time Trained Faculty.', '', 'Faculty', true),
('100', 'RUCHIKA SINGHAL', 'PRT', 'Appointed: 01-07-2024. Status: Probation. Full Time Trained Faculty.', '', 'Faculty', true),
('101', 'VINITA SINGH', 'PRT', 'Appointed: 01-07-2024. Status: Contract. Full Time Trained Faculty.', '', 'Faculty', true),
('102', 'PRAHLAD SINGH', 'PRT', 'Appointed: 01-07-2025. Status: Contract. Full Time Trained Faculty.', '', 'Faculty', true),
('103', 'S.G. MATHEW', 'OFFICE ASSISTANT', 'Appointed: 01-04-2001. Status: Confirmed. Full Time Trained staff.', '', 'Administration', true),
('104', 'BINU JOHN THOMAS', 'ACCOUNTANT', 'Appointed: 01-07-2001. Status: Confirmed. Full Time Trained staff.', '', 'Administration', true),
('105', 'PRATAP LAKRA', 'LIBRARIAN', 'Appointed: 01-09-1997. Status: Confirmed. Full Time Trained staff.', '', 'Administration', true),
('106', 'KURIAKOSE P. PAULOSE', 'CHEMISTRY LAB ASST.', 'Appointed: 01-04-2005. Status: Confirmed. Full Time Trained staff.', '', 'Administration', true),
('107', 'BETCY AJI', 'OFFICE ASSISTANT', 'Appointed: 15-09-2010. Status: Confirmed. Full Time Trained staff.', '', 'Administration', true),
('108', 'BISHNU POKHREL', 'COMPUTER LAB ASST.', 'Appointed: 01-04-2011. Status: Confirmed. Full Time Trained staff.', '', 'Administration', true),
('109', 'NELSON STANLEY THEODORE', 'PA TO PRINCIPAL', 'Appointed: 07-01-2015. Status: Confirmed. Full Time Trained staff.', '', 'Administration', true),
('110', 'NIKHIL ABRAHAM GEORGE', 'ACC. ASST', 'Appointed: 03-07-2017. Status: Confirmed. Full Time Trained staff.', '', 'Administration', true),
('111', 'RAVINDRA SHARMA', 'BIO LAB ASST.', 'Appointed: 01-09-1994. Status: Confirmed. Full Time Trained staff.', '', 'Administration', true);
